# Generated by Django 5.2.5 on 2025-10-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_patientprofile_first_name_patientprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
