# Generated by Django 5.2.5 on 2025-10-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_remove_user_user_type_user_is_doctor_user_is_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='password',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
