# Generated by Django 5.2.5 on 2025-10-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_patientprofile_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='email',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='password',
            field=models.BinaryField(max_length=20, null=True),
        ),
    ]
