# Generated by Django 5.2.5 on 2025-10-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_patientprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
