# Generated by Django 5.2.5 on 2025-10-13 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_remove_doctorprofile_user_remove_patientprofile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='identity',
            field=models.FileField(blank=True, null=True, upload_to='identities/'),
        ),
        migrations.AddField(
            model_name='doctorprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
