# Generated by Django 5.2.5 on 2025-10-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_doctorprofile_birth_date_doctorprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='email',
            field=models.CharField(null=True),
        ),
    ]
