# Generated by Django 5.2.5 on 2025-10-13 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_doctorprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='password',
            field=models.BinaryField(max_length=20, null=True),
        ),
    ]
