# Generated by Django 5.2.5 on 2025-11-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_appointment_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
